### PR TITLE
jsFiddle Workspaces for jQuery Fundamentals Exercises

### PR DESCRIPTION
**Pull request by Suggsgested**
Greetings!

This potential update would add jsFiddle.net integration with jQuery Fundamentals Exercises.
http://jsfiddle.net/

Giving instant access to share jQuery Fundamental exercises online.

jsFiddle.net allows for html/js/css code to be pulled and forked directly from GitHub
http://doc.jsfiddle.net/use/github_read.html

i have formatted the jQuery Fundamentals chapter exercises into jsFiddle GitHub ready demos.

i have added these well formated exercises to exercises/demos to give us links like these: (of course these links will need to change if this commit is accepted to replace my name suggsgested with rmurphey):

CHAPTER 3
http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-3/Selecting/

http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-3/Manipulating/

http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-3/Traversing/

CHAPTER 5
http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-5/InputHint/

http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-5/TabbedNavigation/

CHAPTER 6
http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-6/DropdownMenus/

http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-6/HiddenText/

http://jsfiddle.net/gh/get/jquery/1.5/Suggsgested/jqfundamentals/tree/master/exercises/demos/CHAPTER-6/SlideShow/

---

this integration came from a need to share the jQuery Fundamentals exercises within a course setting at P2PU School of WebCraft

http://p2pu.org/webcraft

http://p2pu.org/webcraft/jquery-love-dollar

### CODE REVIEW

**Comment by rmurphey** [comment]
The consensus is: this is amazing. We'll work on getting this integrated into the repo when we do a sprint the week of March 21, but in the meantime please know it's much appreciated!

**Comment by rmurphey** [comment]
Also: it could be useful to create a jqfundamentals user on jsFiddle, so these don't live under any particular username (including mine :) ).

**Comment by Suggsgested** [comment]
ROCK ON!
Thanks goes to the hard work by zalun (https://github.com/zalun ) for giving us all jsFiddle, but im honored to contribute!
March 21 sounds great... gives me time to work out kinks like the jqfundamentals user that you suggsgest

**Comment by danheberden** [comment]
Suggsgested - I got the new book format ( same, just broken up with a Makefile ) - it shouldn't affect the exercise files but wanted to make sure you pulled master before moving forward on the integration :)

**Comment by Suggsgested** [comment]
thanks dan! 

iv'e pulled master and im ready to go... also FYI ive figured out how to add chapter 7 "Load Ajax Content" exercises to my master and should be ready to do pull request on those today.

jsFiddle has an API that allows for external GitHub hosted Ajax response content (html, json or xml) to be pulled in with Ajax calls... pretty cool.

~ Sean Suggs

**Comment by addyosmani** [comment]
I know it's been a while since this pull request was reviewed, but just going back through the old issues. If we (learn.jquery.com) are happy with using jsFiddle examples for the exercises, which I think would be tremendously useful to users, we should merge these changes into https://github.com/jquery/web-learn-jquery-com. Could you possibly file a pull request against that repo?

**Comment by Suggsgested** [comment]
i would love to! i will wrap my head around where i left off, find your repo and do the pull request today. thanks for your interest, i do think using jsFiddle as a teaching tool has proven to be successful with other projects that i have seen.

**Comment by Suggsgested** [comment]
addyosmani, ive made the pull request that you requested that i request :)
since i last did this initial pull i had added the last of the exercises to the jsFiddle.net links, so those are new and are a part of the new pull request.

enjoy

**Pull request closed without merging**
